### ISSUE TITLE
Add time-based expiry to generic cache

### ISSUE THREAD

**Issue by hasit** [fluxninja/aperture#1345]
**Is your feature request related to a problem? Please describe.**
The generic cache package used to expose `[GetAllAndClear](https://github.com/fluxninja/aperture/blob/2ded8ea8a40d1871a7edb87fdc5c741d603faf40/pkg/cache/cache.go#L33)` to clear the cache at every heartbeat interval.

Now that the list of control points held in generic cache are being fetched by `flowcontrol/controlpoints` API as well, we need to maintain the cache so that empty lists are not returned.

**Describe the solution you'd like**
In order to remove older cache entries (e.g. inactive control points), we need a time-based expiry mechanism.

**Alternatives**
Use a popular, well-maintained cache package (with time-based expiry) instead of managing our own cache package.

**Refer to:**
Generic Cache: https://github.com/fluxninja/aperture/blob/main/pkg/cache/cache.go
Use in heartbeats: https://github.com/fluxninja/aperture/blob/42b04f823f168b34a436d4b4e4b160400076b080/plugins/service/aperture-plugin-fluxninja/heartbeats/heartbeats.go#L229
Use in flowcontrol/controlpoints API: https://github.com/fluxninja/aperture/blob/42b04f823f168b34a436d4b4e4b160400076b080/pkg/policies/flowcontrol/service/controlpoints/controlpoints.go#L30

**Comment by krdln** [comment]
@hasit I agree and disagree simultaneously :D

1. For usage in heartbeats, time-based expiry is overkill and also, a bit imprecise – the `GetAndClear()` approach makes it very straighforward for heartbeats to always send "list of controlpoints active since last heartbeat"
2. For other uses (ad-hoc querying api (directly or via aperturectl)), this is not ideal, as when getting the state you may encouter state "fresh after reset", which might be empty. Perhaps time-based expiry would be better here?

I've quickly tried searching some caches, and found:
* https://github.com/jellydator/ttlcache, 580 starts, non-generic, lacks GetAll, ruled out
* https://pkg.go.dev/github.com/Code-Hex/go-generics-cache, 274 starts, generic, has Keys()
* https://pkg.go.dev/github.com/allegro/bigcache, 6k starts, non-generic, has iterator

I guess there's no clear winner here. Also see https://medium.com/codex/our-go-cache-library-choices-406f2662d6b

I wonder, perhaps the simplest is that we can go back to previous solution, but then to avoid problems with second usecase, keep one historical map in-memory?

**Comment by krdln** [comment]
Note: This affects `aperturectl flow-control control-points` as it might return stale data. Will try to do some quick-fix there.

**Comment by harjotgill** [comment]
@krdln I think we should fix this one way or the other. Thanks!
