### ISSUE TITLE
Add `classifiers` to `flowcontrolv1.CheckResponse`

### ISSUE THREAD

**Issue by kwapik** [fluxninja/aperture#268]
The goal of this ticket is to add `classifiers` to the `flowcontrolv1.CheckResponse` proto message.

Useful links:
1. [Proto message to modify](https://github.com/fluxninja/aperture/blob/main/api/aperture/flowcontrol/v1/flowcontrol.proto#L19)
2. [Authz response to be extended](https://github.com/fluxninja/aperture/blob/main/pkg/flowcontrol/envoy/authz.go#L120)
3. [`ProcessRequest` func to modify to populate classifiers](https://github.com/fluxninja/aperture/blob/5783cd55dc0a60bb7f65fae8e365ab07b115371c/pkg/policies/dataplane/engine.go#L58)
4. [Envoy config to be updated](https://github.com/fluxninja/aperture/blob/5783cd55dc0a60bb7f65fae8e365ab07b115371c/manifests/charts/istioconfig/templates/envoy_filter.yaml#L26)

**Comment by DariaKunoichi** [comment]
Prepared a PR for that: https://github.com/fluxninja/aperture/pull/310
Could not test because of recent changes in Tilt.
I also think that ClassifierID should have something more in it than policyName and policyHash. Can we use rulesetName? Or maybe a list of labels in this particular classifiers (may be too long for ID).
@kwapik
