### ISSUE TITLE
Change default HTTP flow labels in Selector to be consistent with OTEL semantic conventions

### ISSUE THREAD

**Issue by tanveergill** [fluxninja/aperture#341]
**Describe the solution you'd like**
* Default HTTP flow labels are defined [here](https://github.com/fluxninja/aperture/blob/ebd73a5f53515fc0fb1db318b7cc5bffef6ee73e/pkg/selectors/labels.go#L60)
* Default label names need to follow [OTEL's semantic conventions for HTTP related fields](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#common-attributes) 

---

See list in comment below for exact details:
- [x] Simply rename "easy" fields
- [x] Remove `request_id`
- [x] Let's stay with "fictional" `http.host` attribute for now
- [x] Convert `scheme` to `http.flavor` to fit OTEL conventions (btw, let's do it also in metrics pipeline)
- [x] Don't forget to underscorize headers
- [x] Document it: https://docs.fluxninja.com/docs/development/concepts/flow-control/label/#request-labels
  (I (@krdln) can do it)
- [ ] Blueprints PR! https://github.com/fluxninja/aperture-blueprints/pull/26

---

Start here https://github.com/fluxninja/aperture/blob/main/pkg/selectors/labels.go

**Comment by krdln** [comment]
I guess the goal here is to unify naming in druid with names of request flow labels, so that one could more easily write policies after analysing data in druid.

I'm not sure sticking with OTEL conventions is a good idea though, as there are some weird edge-cases. OTEL's spec is still WIP and documentation is a bit chaotic (remember, we need to document all the fields or refer user to some other piece of docs, and I think [envoy docs](https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/auth/v3/attribute_context.proto#service-auth-v3-attributecontext-httprequest) are nicer here).

**Comment by tanveergill** [comment]
@krdln,

Flow classifier would work differently for each service mesh or middleware tech. and the user understands the expectation.

Where Druid telemetry is concerned, lets follow uniform naming convention per protocol level field regardless of the underlying source of telemetry (Envoy, Kong, Nginx etc.)

If there are some special Envoy specific field, like `net.host.name` let them be the same in Druid telemetry. As we have dynamic schema in Druid and can allow middleware specific fields wherever required, else, stick to the protocol level conventions for uniformity across different sources of telemetry - this would ensure that the same protocol level Grafana dashboards works for all sources
